<a href="https://colab.research.google.com/github/mirellac17/PCM_python/blob/main/Copia_de_numpy_PCM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Librerías en Python
Muchas funciones relacionadas entre sí pueden asociarse en un bloque única. Este conjunto recibe el nombre de 'librería' (y viene acompañada de otros elementos llamados objetos y clases, esto escapa al paradigma de programación que estamos viendo) . Existen librerías especializadas en distintas tareas. Nos enfocaremos en la libería Numpy, que es una de las importantes para realizar tareas de análisis de datos.


#Librería Numpy
Numpy (Numerical Python) es la librería para manipular vectores y matrices, y realizar operaciones entre estas. Es necesario tener el cuenta que gran parte de procesos estadísticos son operaciones matriciales. Además, posee diversas aplicaciones en otro campos como la visión por computadora o procesamiento del lenguaje natural.


In [ ]:
import numpy as np
#arrays
vector1 = np.array([10,30,-2,40,-2])
vector2 = np.arange(0,10,0.1)
vector3 = np.linspace(0,10,101)
print(vector1)
print(vector2)
print(vector3)

[10 30 -2 40 -2]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [ ]:
#El acceso a los elementos es igual que al de las listas
print(vector1[0])
print(vector2[0])
print(vector3[0])
print(vector3[-1])
print(vector3[5:19])


10
0.0
0.0
10.0
[0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([-2,3,0,2,1])
print(a,b)
print(5*a)
print(-2*b)
print(a+b)
print(a*b) #multiplicacion elemento a elemento
print(np.dot(a,b)) #producto punto


[1 2 3 4 5] [-2  3  0  2  1]
[ 5 10 15 20 25]
[ 4 -6  0 -4 -2]
[-1  5  3  6  6]
[-2  6  0  8  5]
17


In [ ]:
#Matrices
matrizA = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrizA)

matrizB = np.matrix([
    [10,-2,3],
    [-1,9,2],
    [1,0,-2]
])

print(matrizB)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 -2  3]
 [-1  9  2]
 [ 1  0 -2]]


Numpy incluye una amplia variedad de operaciones que se pueden realizar sobre matrices. Es importante tener en cuenta que estas operaciones tienen múltiples aplicaciones en diversos campos como en la solución de ecuaciones, solución de ecuaciones diferenciales, problemas de regresión y extrapolación, etc.

A continuación exploraremos algunas de las funciones más importantes:

In [ ]:
#suma de matrices
print(matrizA+matrizB)
#producto de matrices
print(np.matmul(matrizA,matrizB))
print(np.matmul(matrizB,matrizA))
#matriz identidad
print(np.identity(5))


[[11  0  6]
 [ 3 14  8]
 [ 8  8  7]]
[[11 16  1]
 [41 37 10]
 [71 58 19]]
[[ 23  34  45]
 [ 49  59  69]
 [-13 -14 -15]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejemplo:
Resuelva matricialmente el siguiente sistema de ecuaciones.

$2 x + y = 4$

$-3x + 2y = 1$

Recuerde que esta ecuación puede colocarse en la forma AX=B donde:

$A = \begin{pmatrix}
2 & 1 \\
-3 & 2
\end{pmatrix}$

$B=\begin{pmatrix}
x \\
y
\end{pmatrix}$

$C=\begin{pmatrix}
4 \\
1
\end{pmatrix}$

Por lo que el sistema de ecuaciones queda como:

$\begin{pmatrix}
2 & 1 \\
-3 & 2
\end{pmatrix}
\begin{pmatrix}
x \\
y
\end{pmatrix}=\begin{pmatrix}
4 \\
1
\end{pmatrix}$

Es importante recordar que necesitamos calcular los valores de la matriz X, esta queda dada por:

$X = A^{-1} B$

Esto quiere decir que necesitamos calcular la inversa de la matriz A (denotado como $A^{-1}$) y multiplicarla por B.

Una vez calculado esto, usted está en capacidad de hay una función que resulva sistemas de ecuaciones lineales si se le da como valores de entrara la matriz A y B.